name: League Mythic Shop Updates

on:
  schedule:
    - cron: "0 14 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  mythic-shop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Restore Mythic Shop state
        uses: actions/cache/restore@v4
        with:
          path: check/mythic-shop/mythic-shop-state.json
          key: mythic-shop-state-${{ github.run_id }}
          restore-keys: |
            mythic-shop-state-

      - name: Run Mythic Shop checker
        run: npm run mythic-shop
        env:
          MYTHIC_SHOP_WEBHOOK_URL: ${{ secrets.MYTHIC_SHOP_WEBHOOK_URL }}
          ERROR_WEBHOOK_URL: ${{ secrets.ERROR_WEBHOOK_URL }}
          SEND_TO_DISCORD: "true"

      - name: Save Mythic Shop state
        if: always()
        uses: actions/cache/save@v4
        with:
          path: check/mythic-shop/mythic-shop-state.json
          key: mythic-shop-state-${{ github.run_id }}
