name: League Mythic Shop Updates

on:
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  mythic-shop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run Mythic Shop checker
        run: node mythic-shop-check.js
        env:
          VPBE_WEBHOOK_URL: ${{ secrets.MYTHIC_SHOP_WEBHOOK_URL }}
          ERROR_WEBHOOK_URL: ${{ secrets.ERROR_WEBHOOK_URL }}
          SEND_TO_DISCORD: "true"

      - name: Commit Mythic Shop state
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add check/mythic-shop/mythic-shop-state.json
          git commit -m "update mythic shop state" || echo "No mythic shop state changes"

          git pull --rebase
          git push
