name: League Skin Sale Updates

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  skin-sale:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run skin sale checker
        run: node skin-sale-check.js
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.SKIN_SALE_WEBHOOK_URL }}
          ERROR_WEBHOOK_URL: ${{ secrets.ERROR_WEBHOOK_URL }}

      - name: Commit skin sale state
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add check/skin-sale/skin-sale-state.json
          git commit -m "update skin sale state" || echo "No skin sale state changes"

          git pull --rebase
          git push
