name: League Newest Skins Updates

on:
  schedule:
    - cron: "0 9 */3 * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  skin-newest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Chromium
        run: npx playwright install --with-deps chromium

      - name: Restore newest skins state
        uses: actions/cache/restore@v4
        with:
          path: check/skin-newest/skin-newest-state.json
          key: skin-newest-state-${{ github.run_id }}
          restore-keys: |
            skin-newest-state-

      - name: Run newest skins checker
        run: npm run skin:newest
        env:
          SKIN_NEWEST_WEBHOOK_URL: ${{ secrets.SKIN_NEWEST_WEBHOOK_URL }}
          SKIN_SALE_WEBHOOK_URL: ${{ secrets.SKIN_SALE_WEBHOOK_URL }}
          ERROR_WEBHOOK_URL: ${{ secrets.ERROR_WEBHOOK_URL }}
          SEND_TO_DISCORD: "true"

      - name: Save newest skins state
        if: always()
        uses: actions/cache/save@v4
        with:
          path: check/skin-newest/skin-newest-state.json
          key: skin-newest-state-${{ github.run_id }}
